# Generated by Django 6.0.2 on 2026-02-28 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=10)),
                ('empresa', models.CharField(blank=True, default='', max_length=200)),
                ('setor', models.CharField(blank=True, default='', max_length=100)),
                ('modelo_veiculo', models.CharField(blank=True, default='', max_length=200)),
                ('data_abertura', models.DateTimeField()),
                ('data_previsao', models.DateTimeField(blank=True, null=True)),
                ('data_encerramento', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('status', models.CharField(max_length=50)),
                ('flag_especial', models.BooleanField(default=False)),
                ('valor_pecas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_servicos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('veiculo', models.ForeignKey(db_column='placa', on_delete=django.db.models.deletion.PROTECT, related_name='manutencoes', to='veiculos.veiculo', to_field='placa')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orcamento', models.IntegerField(unique=True)),
                ('data', models.DateField()),
                ('oficina', models.CharField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=30)),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='manutencoes.manutencao')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'ordering': ['codigo_orcamento'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3)),
                ('grupo', models.CharField(blank=True, default='', max_length=100)),
                ('codigo_item', models.CharField(blank=True, default='', max_length=50)),
                ('descricao', models.CharField(max_length=300)),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('valor_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qtd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('garantia', models.DateField(blank=True, null=True)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='manutencoes.orcamento')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'ordering': ['tipo', 'descricao'],
            },
        ),
    ]
