# Generated by Django 6.0.2 on 2026-03-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='previsao_em_dias',
            field=models.IntegerField(default=0),
        ),
    ]
