# Generated by Django 6.0.2 on 2026-03-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0002_orcamento_previsao_em_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='fim_execucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='inicio_execucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
