# Generated by Django 6.0.2 on 2026-03-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencoes', '0003_manutencao_fim_execucao_manutencao_inicio_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='data_integracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
