# Generated by Django 6.0.2 on 2026-03-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.CharField(blank=True, default='', max_length=500)),
                ('descricao', models.CharField(blank=True, default='', max_length=300)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração geral',
                'verbose_name_plural': 'Configurações gerais',
                'ordering': ['chave'],
            },
        ),
    ]
