# Generated by Django 6.0.2 on 2026-02-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=200)),
                ('unidade', models.CharField(blank=True, default='', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['placa'],
            },
        ),
    ]
