# Generated by Django 6.0.2 on 2026-03-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='unidade',
            field=models.CharField(blank=True, default='FUB', max_length=100),
        ),
    ]
