# Generated by Django 6.0.2 on 2026-03-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_veiculo_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
    ]
