# Generated by Django 6.0.2 on 2026-03-03 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_infracao', models.CharField(max_length=50, unique=True)),
                ('orgao_autuador', models.CharField(blank=True, default='', max_length=200)),
                ('data_infracao', models.DateField()),
                ('hora_infracao', models.TimeField(blank=True, null=True)),
                ('descricao_infracao', models.TextField(blank=True, default='')),
                ('local_infracao', models.CharField(blank=True, default='', max_length=300)),
                ('data_notificacao', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('protocolo_sei', models.CharField(blank=True, default='', max_length=100)),
                ('situacao', models.CharField(choices=[('EM ABERTO', 'Em Aberto'), ('PAGA', 'Paga'), ('CONTESTADA', 'Contestada'), ('BAIXADA', 'Baixada')], default='EM ABERTO', max_length=20)),
                ('observacao', models.TextField(blank=True, default='')),
                ('veiculo', models.ForeignKey(db_column='placa', on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='veiculos.veiculo', to_field='placa')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'ordering': ['-data_infracao'],
            },
        ),
    ]
