# Generated by Django 6.0.2 on 2026-03-21 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manutencoes', '0004_manutencao_data_integracao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('VALOR_ALTO', 'Valor alto'), ('PRAZO_EXCEDIDO', 'Prazo excedido'), ('REINCIDENCIA', 'Reincidência de problema'), ('GARANTIA', 'Em garantia'), ('VEICULO_CRITICO', 'Veículo crítico'), ('ORCAMENTO_DIVERGENTE', 'Orçamento divergente'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30)),
                ('prioridade', models.IntegerField(choices=[(1, 'Alta'), (2, 'Média'), (3, 'Baixa')], default=2)),
                ('observacao', models.TextField(blank=True, default='')),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='manutencoes.manutencao', to_field='numero_os')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acompanhamento',
                'verbose_name_plural': 'Acompanhamentos',
                'ordering': ['finalizado', 'prioridade', 'data_limite'],
                'unique_together': {('usuario', 'manutencao')},
            },
        ),
    ]
