# Generated by Django 6.0.2 on 2026-02-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado_em', models.DateTimeField(auto_now=True, verbose_name='realizado em')),
            ],
            options={
                'verbose_name': 'registro de importação',
                'verbose_name_plural': 'registros de importação',
            },
        ),
    ]
